name: CI
on: repository_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with: 
        token: ${{ secrets.TOKEN }}
        submodules: true 
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Run a multi-line script
      run: |
        cd sdk
        npm install
        npm run gen-docs-wechat
        ls ./docs
